groups:
  - name: example
    rules:
      - alert: HighRequestRate
        expr: sum(rate(http_requests_total{job="apache"}[1m])) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High request rate detected
          description: '{{ $value }} requests per second for Apache server exceeded threshold'

      - alert: HighMySQLConnections
        expr: mysql_global_connections > 500
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High MySQL connections detected
          description: '{{ $value }} active connections to MySQL server exceeded threshold'

      - alert: HighPostgreSQLConnections
        expr: pg_stat_activity_connections > 200
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High PostgreSQL connections detected
          description: '{{ $value }} active connections to PostgreSQL server exceeded threshold'
